# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Laboratoire d’Algèbre, de Combinatoire et d’Informatique Mathématique (LACIM)
email: lacim@uqam.ca
description: >- # this means to ignore newlines until "baseurl:"
  Le LACIM est un centre de recherche institutionnel de l'UQAM regroupant
  chercheurs dont les grands thèmes de recherche puisent leurs origines dans la
  combinatoire et ses liens avec l'algèbre et l'informatique.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lacim.uqam.ca" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  lacim-uqam

#######################################################################
#                        Localization Settings                        #
#######################################################################

defaults:
  -
    scope:
      path: en
    values:
      lang: en
      other_language:
        name: Français
        path: fr
  -
    scope:
      path: fr
    values:
      lang: fr
      other_language:
        name: English
        path: en


#######################################################################
#                           Build Settings                            #
#######################################################################

theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

